/* Copyright (C) 2010, University of Halle */

/*  This file is part of Sather-K Compiler Halle.
      
    Sather-K Compiler Halle is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
                      
    Sather-K Compiler Halle is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
                                      
    You should have received a copy of the GNU General Public
    License along with Sather-K Compiler Halle.  If not, see
    <http://www.gnu.org/licenses/>. */
    

/* interface of tree construction functions */

#ifndef TREECON_H
#define TREECON_H
#include "eliproto.h"

#include "err.h"

#include "nodeptr.h"

#include "HEAD.h"


extern void InitTree ELI_ARG((void));

extern void FreeTree ELI_ARG((void));

extern NODEPTR Mktypes ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkwhen_types_block ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkwhen_types_blocks ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mktype_case_statement ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkInheritance_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_argument_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkType_specifiers_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_parameter_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkTypes ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkWhen_types_block ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkCase_label ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkLabel_range ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkLabel_list ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkWhen_label_stmt ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkWhen_label_stmts ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkException_types ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkWhen_exception_stmt ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkWhen_exception_stmts ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkExceptions ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkAssertion_statement ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkRaise_statement ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkReturn_statement ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkResume_statement ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBreak_statement ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkLoop ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkCase_statement ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkConditional_statement ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBegin_block ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkAssignment ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkLocal_stream_declaration ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkStatements ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBuiltin_instruction ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkLinker_symbol ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkForeign_language ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBlock ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkStringconstant ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkStringconstants ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkNamed_expression ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkAgg_id_def ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkNamed_expressions ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkAggregate ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkQual_feature_id_use ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkObj_id_use ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkDirect_stream_call ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkCoercion ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkValue ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBound_method ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkQualification ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkStd_method_call ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkName ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkDesignator ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkArgument ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkArguments ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkParameter_type ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkParameter_types ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkParameter_type_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkParameter_types_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBounds ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_argument ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkType_specifiers ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_parameter ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkMethod_specification ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkFeature_specification ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkFeature_id_use ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkIdent_mod ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkModification ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkstatements ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkbuiltin_instruction ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkbuiltin_instructions ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mklinker_symbol ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkforeign_language ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkparameter_specification ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkmethod_body ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkparameters ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkmethod_ident_def ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkmethod_decl ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkreturn_statement ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkresume_statement ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkbreak_statement ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkloop ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkLocal_declarations ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkWhen_types_blocks ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkType_case_statement ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkParameter_kind ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkParameter_specification ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkType_constructor ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBuiltin_instructions ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkType_specifier ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkParameters ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkMethod_ident_def ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkFeature_declaration ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkMethod_body ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkAttribute_specification ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkAttribute_declaration ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkAttribute_access_type ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkIdentifiers ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkMethod_decl ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkFeature ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_id_use ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_specifier ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkFeature_declarations ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBuiltin_option ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_body ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_attribute ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkIdent_def ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBound_identifier ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_parameters ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_bounds ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_id_def ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_declaration ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_head ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkModifications ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_arguments ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkInheritances ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkInheritance ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkExpression ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBound ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mklocal_stream_declaration ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mklocal_declarations ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkfeature_declaration ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkqual_feature_id_use ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkobj_id_use ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkqualification ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkdirect_stream_call ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkstd_method_call ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkcoercion ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkargument ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkbound_method ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkarguments ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkstringconstant ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkstringconstants ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkconditional_statement ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkStringconstant_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkStringconstants_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_arguments_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_id_use_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBound_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBounds_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkWhen_types_blocks_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkResume_statement_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkType_case_statement_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkObj_id_use_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkWhen_types_block_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkReturn_statement_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkQual_feature_id_use_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkParameter_kind_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkParameter_specification_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkLinker_symbol_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkForeign_language_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkInheritances_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBreak_statement_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkLoop_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkMethod_body_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkParameters_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkMethod_ident_def_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkMethod_decl_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkFeature_declarations_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkDirect_stream_call_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkValue_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkRaise_statement_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkWhen_exception_stmt_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkWhen_exception_stmts_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBegin_block_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkExceptions_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkQualification_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkStd_method_call_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkConditional_statement_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkCoercion_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_parameters_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_id_def_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_body_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_head_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_attribute_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkCase_label_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkLabel_range_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkLabel_list_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkWhen_label_stmts_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkWhen_label_stmt_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkCase_statement_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBuiltin_instruction_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBuiltin_instructions_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkMethod_specification_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBound_method_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkLocal_stream_declaration_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkStatements_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkLocal_declarations_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBlock_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBound_identifier_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_bounds_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkFeature_declaration_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkAttribute_specification_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkIdent_def_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkAttribute_declaration_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkAttribute_access_type_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkType_specifier_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkIdentifiers_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkFeature_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkAssignment_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkAssertion_statement_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkDesignator_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkArgument_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkArguments_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkExpression_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkName_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkNamed_expression_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkAgg_id_def_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkNamed_expressions_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkAggregate_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkType_constructor_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_specifier_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_declaration_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkBuiltin_option_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkparameter_kind ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkparameter_type ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkparameter_types ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkfeature_id_use ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkident_mod ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkfeature_specification ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkmodification ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkmodifications ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkinheritance ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkfeature_declarations ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkinheritances ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkbuiltin_option ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkclass_argument ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkclass_arguments ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkmethod_specification ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkclass_specifier ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mktype_specifiers ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkclass_parameter ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkbound_identifier ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkclass_id_use ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkclass_param_id_def ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkclass_parameters ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkclass_bounds ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkclass_id_def ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkclass_body ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkclass_head ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkclass_attribute ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkclass_declaration ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_declarations_2 ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR MkClass_declarations ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkclass_declarations ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkprogram ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkdesignator ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkvalue ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkcase_label ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mklabel_range ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mklabel_list ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkwhen_label_stmt ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkwhen_label_stmts ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkcase_statement ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkbound ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkbounds ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkassertion_statement ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkraise_statement ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkexception_types ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkwhen_exception_stmt ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkwhen_exception_stmts ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkexceptions ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkblock ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkbegin_block ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkident_def ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mktype_specifier ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mktype_constructor ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkidentifiers ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkattribute_specification ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkattribute_declaration ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkfeature ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkattribute_access_type ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkassignment ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkexpression ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkname ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mknamed_expression ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkagg_id_def ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mknamed_expressions ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkaggregate ELI_ARG((POSITION *_coordref, NODEPTR _currn));
extern NODEPTR Mkrule_1 ELI_ARG((POSITION *_coordref));
extern NODEPTR Mkrule_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkASSERTION_STATEMENT_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkRAISE_STATEMENT_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkRETURN_STATEMENT_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkRESUME_STATEMENT_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBREAK_STATEMENT_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkLOOP_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkLOOP_EXP_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkTYPES_LST_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkTYPES_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkWHEN_TYPES_BLOCK_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkWHEN_TYPES_BLOCKS_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkWHEN_TYPES_BLOCKS_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkTYPE_CASE_STATEMENT_ATT_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkTYPE_CASE_STATEMENT_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCASE_LABEL_DES_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkCASE_LABEL_VALUE_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkLABEL_RANGE_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkLABEL_RANGE_SINGLE_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
#define Mk0LABEL_LIST_O(_coordref) NULLNODEPTR
extern NODEPTR Mk2LABEL_LIST_O ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkLABEL_LIST_O ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkWHEN_LABEL_STMT_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkWHEN_LABEL_STMTS_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkWHEN_LABEL_STMTS_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCASE_STATEMENT_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCOND_STATEMENT_ELSE_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkCOND_STATEMENT_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkEXCEPTION_TYPES_LST_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkEXCEPTION_TYPES_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkWHEN_EXCEPTION_STMT_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkWHEN_EXCEPTION_STMTS_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkWHEN_EXCEPTION_STMTS_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkEXCEPTIONS_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkEXCEPTIONS_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBEGIN_BLOCK_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkASSIGNMENT_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_ASSERT_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_RAISE_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_RETURN_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_RESUME_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_EXP_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_BREAK_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_LOOP_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_TYPE_CASE_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_CASE_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_COND_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_BEGIN_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_ASSIGN_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkLOCAL_STREAM_DECL_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkLOCAL_DECLS_STREAM_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkLOCAL_DECLS_ATT_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkLOCAL_DECLS_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBLOCK_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkBUILTIN_INST_CLRTYPE_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkBUILTIN_INST_TYPE_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkBUILTIN_INST_STR_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBUILTIN_INSTS_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBUILTIN_INSTS_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkMETHOD_BODY_STATIC_BUILTIN_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkMETHOD_BODY_BUILTIN_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkLINKER_SYMBOL_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkLINKER_SYMBOL_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkFOREIGN_LANGUAGE_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkMETHOD_BODY_FOREIGN_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkMETHOD_BODY_AB_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkMETHOD_BODY_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkPARAMETER_SPEC_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
#define Mk0PARAMETERS_O(_coordref) NULLNODEPTR
extern NODEPTR Mk2PARAMETERS_O ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkPARAMETERS_O ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkMETHOD_IDENT_DEF_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkMETHOD_DECL_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3, NODEPTR _desc4));
extern NODEPTR MkIDENTIFIERS_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkIDENTIFIERS_LST_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_SPEC_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_DECL_CONST_TYPE_CONST_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_DECL_TYPE_CONST_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_DECL_CONST_EXP_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_DECL_EXP_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_DECL_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkATTR_ACCESS_SH_RO_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkATTR_ACCESS_RO_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkATTR_ACCESS_SH_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkFEATURE_STREAM_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkFEATURE_METH_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkFEATURE_ATT_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkFEATURE_ATT_ACC_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkFEATURE_DECL_PRIV_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkFEATURE_DECL_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
#define Mk0FEATURE_DECLS_O(_coordref) NULLNODEPTR
extern NODEPTR Mk2FEATURE_DECLS_O ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkFEATURE_DECLS_O ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkFEATURE_ID_USE_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkFEATURE_SPEC_STREAM_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkFEATURE_SPEC_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkIDENT_MOD_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkMODIFICATION_NAME_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkMODIFICATION_OUT_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkMODIFICATION_ONLY_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
#define Mk0MODIFICATIONS_O(_coordref) NULLNODEPTR
extern NODEPTR Mk2MODIFICATIONS_O ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkMODIFICATIONS_O ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkINHERITANCE_INC_ONLY_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkINHERITANCE_INCLUDE_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkINHERITANCE_LIKE_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkINHERITANCE_PRIV_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkINHERITANCES_LST_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkINHERITANCES_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkDIRECT_STREAM_CALL_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCOERCION_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTR_CONSTANT_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkSTR_CONSTANTS_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkSTR_CONSTANTS_LST_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkVALUE_VOID_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkVALUE_SED_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkVALUE_OCT_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkVALUE_STR_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkVALUE_CHAR_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkVALUE_BOOL_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkVALUE_FLOAT_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkVALUE_INT_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBOUND_METHOD_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkNAMED_EXPRESSION_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
#define Mk0NAMED_EXPRESSIONS_O(_coordref) NULLNODEPTR
extern NODEPTR Mk2NAMED_EXPRESSIONS_O ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkNAMED_EXPRESSIONS_O ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkAGG_ID_DEF_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkAGGREGATE_NAMED_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkAGGREGATE_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_CONSTRUCTOR_SAME_AGG_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_CONSTRUCTOR_SAME_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_CONSTRUCTOR_DES_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkTYPE_CONSTRUCTOR_AGG_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_CONSTRUCTOR_CLASS_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3, NODEPTR _desc4));
extern NODEPTR MkTYPE_CONSTRUCTOR_CL_AGG_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3, NODEPTR _desc4));
extern NODEPTR MkQUAL_FEATURE_ID_USE_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkQUALIFICATION_TYPE_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkQUALIFICATION_EXP_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTD_METHOD_CALL_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkOBJ_ID_USE_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkNAME_NOT_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_POW_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_MOD_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_DIV_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_QUOTIENT_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_STAR_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkNAME_MINUS_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_PLUS_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_GT_EQ_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_GT_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_LT_EQ_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_LT_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_NOT_EQ_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_EQ_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_QUESTION_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_GRAVE_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_TILDE_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_STROKE_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_BACKSLASH_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_STR_IN_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_STR_OUT_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_OBJ_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkNAME_LEFT_SQ_BRACKET_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkEXPRESSION_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkEXPRESSION_AND_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkEXPRESSION_OR_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkEXPRESSION_STREAM_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_METH_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_COERCION_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_VALUE_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_BOUND_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_CONS_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_STAR_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkDESIGNATOR_QUAL_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkDESIGNATOR_METH_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkDESIGNATOR_EXP_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkDESIGNATOR_NAME_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkARGUMENT_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkARGUMENT_INOUT_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkARGUMENT_OUT_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkARGUMENT_EXP_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkARGUMENTS_LST_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkARGUMENTS_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBOUND_EXP_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
#define Mk0BOUNDS_O(_coordref) NULLNODEPTR
extern NODEPTR Mk2BOUNDS_O ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkBOUNDS_O ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkCLASS_ID_USE_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkPARAMETER_KIND_INOUT_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkPARAMETER_KIND_OUT_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkPARAMETER_KIND_ONCE_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkPARAMETER_KIND_IN_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkPARAMETER_TYPE_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
#define Mk0PARAMETER_TYPES_O(_coordref) NULLNODEPTR
extern NODEPTR Mk2PARAMETER_TYPES_O ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkPARAMETER_TYPES_O ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkMETHOD_SPECIFICATION_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCLASS_ARGUMENT_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkCLASS_ARGUMENTS_LST_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCLASS_ARGUMENTS_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_SPECIFIER_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkTYPE_SPECIFIER_STREAM_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_SPECIFIER_SAME_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkTYPE_SPECIFIER_SAME_POLY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkTYPE_SPECIFIER_PROC_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_SPECIFIER_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkTYPE_SPECIFIER_DES_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkTYPE_SPECIFIER_CL_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_SPECIFIER_CL_POLY_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_SPECIFIERS_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkTYPE_SPECIFIERS_LST_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCLASS_PARAM_ID_DEF_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkCLASS_PARAMETER_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkIDENT_DEF_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBOUND_IDENTIFIER_STAR_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBOUND_IDENTIFIER_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkCLASS_PARAMETERS_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_PARAMETERS_LST_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCLASS_BOUNDS_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_BOUNDS_LST_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCLASS_ID_DEF_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBUILTIN_OPT_CL_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkBUILTIN_OPT_ID_O ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBUILTIN_OPT_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBUILTIN_OPT_EMPTY_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_BODY_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkCLASS_HEAD_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkCLASS_ATTRIBUTE_VA_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_ATTRIBUTE_EX_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_ATTRIBUTE_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_ATTRIBUTE_ABVA_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_ATTRIBUTE_AB_O ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_DECLARATION_O ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
#define Mk0CLASS_DECLARATIONS_O(_coordref) NULLNODEPTR
extern NODEPTR Mk2CLASS_DECLARATIONS_O ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkCLASS_DECLARATIONS_O ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkASSERTION_STATEMENT_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkRAISE_STATEMENT_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkRETURN_STATEMENT_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkRESUME_STATEMENT_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBREAK_STATEMENT_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkLOOP_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkLOOP_EXP_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkWHEN_TYPES_BLOCK_ELSE_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkWHEN_TYPES_BLOCK_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkWHEN_TYPES_BLOCKS_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkWHEN_TYPES_BLOCKS_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkTYPE_CASE_STATEMENT_ATT_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkTYPE_CASE_STATEMENT_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCASE_LABEL_DES_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkCASE_LABEL_VALUE_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkLABEL_RANGE_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkLABEL_RANGE_SINGLE_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
#define Mk0LABEL_LIST_2(_coordref) NULLNODEPTR
extern NODEPTR Mk2LABEL_LIST_2 ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkLABEL_LIST_2 ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkWHEN_LABEL_STMT_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkWHEN_LABEL_STMTS_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkWHEN_LABEL_STMTS_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCASE_STATEMENT_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCOND_STATEMENT_ELSE_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkCOND_STATEMENT_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkWHEN_EXCEPTION_STMT_ELSE_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkWHEN_EXCEPTION_STMT_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkWHEN_EXCEPTION_STMTS_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkWHEN_EXCEPTION_STMTS_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkEXCEPTIONS_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkEXCEPTIONS_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBEGIN_BLOCK_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkASSIGNMENT_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_ASSERT_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_RAISE_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_RETURN_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_RESUME_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_EXP_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_BREAK_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_LOOP_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_TYPE_CASE_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_CASE_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_COND_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_BEGIN_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_ASSIGN_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkLOCAL_STREAM_DECL_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkLOCAL_DECLS_STREAM_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkLOCAL_DECLS_ATT_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkLOCAL_DECLS_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBLOCK_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkBUILTIN_INST_CLRTYPE_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkBUILTIN_INST_TYPE_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkBUILTIN_INST_STR_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBUILTIN_INSTS_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBUILTIN_INSTS_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkMETHOD_BODY_STATIC_BUILTIN_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkMETHOD_BODY_BUILTIN_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkLINKER_SYMBOL_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkLINKER_SYMBOL_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkFOREIGN_LANGUAGE_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkMETHOD_BODY_FOREIGN_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkMETHOD_BODY_AB_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkMETHOD_BODY_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkPARAMETER_SPEC_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
#define Mk0PARAMETERS_2(_coordref) NULLNODEPTR
extern NODEPTR Mk2PARAMETERS_2 ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkPARAMETERS_2 ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkMETHOD_IDENT_DEF_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkMETHOD_DECL_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3, NODEPTR _desc4));
extern NODEPTR MkIDENTIFIERS_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkIDENTIFIERS_LST_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_SPEC_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_DECL_CONST_TYPE_CONST_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_DECL_TYPE_CONST_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_DECL_CONST_EXP_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_DECL_EXP_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_DECL_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkATTR_ACCESS_SH_RO_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkATTR_ACCESS_RO_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkATTR_ACCESS_SH_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkFEATURE_STREAM_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkFEATURE_METH_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkFEATURE_ATT_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkFEATURE_ATT_ACC_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkFEATURE_DECL_PRIV_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkFEATURE_DECL_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
#define Mk0FEATURE_DECLS_2(_coordref) NULLNODEPTR
extern NODEPTR Mk2FEATURE_DECLS_2 ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkFEATURE_DECLS_2 ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkINHERITANCE_LIKE_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkINHERITANCES_LST_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkINHERITANCES_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkDIRECT_STREAM_CALL_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCOERCION_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTR_CONSTANT_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkSTR_CONSTANTS_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkSTR_CONSTANTS_LST_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkVALUE_VOID_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkVALUE_SED_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkVALUE_OCT_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkVALUE_STR_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkVALUE_CHAR_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkVALUE_BOOL_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkVALUE_FLOAT_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkVALUE_INT_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBOUND_METHOD_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkNAMED_EXPRESSION_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
#define Mk0NAMED_EXPRESSIONS_2(_coordref) NULLNODEPTR
extern NODEPTR Mk2NAMED_EXPRESSIONS_2 ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkNAMED_EXPRESSIONS_2 ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkAGG_ID_DEF_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkAGGREGATE_NAMED_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkAGGREGATE_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_CONSTRUCTOR_SAME_AGG_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_CONSTRUCTOR_SAME_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_CONSTRUCTOR_DES_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkTYPE_CONSTRUCTOR_AGG_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_CONSTRUCTOR_CLASS_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkTYPE_CONSTRUCTOR_CL_AGG_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkQUAL_FEATURE_ID_USE_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkQUALIFICATION_TYPE_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkQUALIFICATION_EXP_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTD_METHOD_CALL_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkOBJ_ID_USE_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkNAME_NOT_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_POW_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_MOD_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_DIV_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_QUOTIENT_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_STAR_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkNAME_MINUS_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_PLUS_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_GT_EQ_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_GT_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_LT_EQ_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_LT_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_EQ_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_QUESTION_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_GRAVE_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_TILDE_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_STROKE_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_BACKSLASH_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_STR_IN_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_STR_OUT_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_OBJ_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkNAME_LEFT_SQ_BRACKET_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkEXPRESSION_AND_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkEXPRESSION_OR_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkEXPRESSION_STREAM_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_METH_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_COERCION_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_VALUE_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_BOUND_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_CONS_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_STAR_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkDESIGNATOR_QUAL_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkDESIGNATOR_METH_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkDESIGNATOR_EXP_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkDESIGNATOR_NAME_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkARGUMENT_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkARGUMENT_INOUT_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkARGUMENT_OUT_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkARGUMENT_EXP_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkARGUMENTS_LST_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkARGUMENTS_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBOUND_EXP_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
#define Mk0BOUNDS_2(_coordref) NULLNODEPTR
extern NODEPTR Mk2BOUNDS_2 ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkBOUNDS_2 ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkCLASS_ID_USE_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkPARAMETER_KIND_INOUT_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkPARAMETER_KIND_OUT_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkPARAMETER_KIND_ONCE_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkPARAMETER_KIND_IN_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkPARAMETER_TYPE_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
#define Mk0PARAMETER_TYPES_2(_coordref) NULLNODEPTR
extern NODEPTR Mk2PARAMETER_TYPES_2 ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkPARAMETER_TYPES_2 ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkMETHOD_SPECIFICATION_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCLASS_ARGUMENT_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkCLASS_ARGUMENTS_LST_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCLASS_ARGUMENTS_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_SPECIFIER_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkTYPE_SPECIFIER_STREAM_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_SPECIFIER_SAME_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkTYPE_SPECIFIER_SAME_POLY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkTYPE_SPECIFIER_PROC_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_SPECIFIER_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkTYPE_SPECIFIER_CL_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_SPECIFIER_CL_POLY_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_SPECIFIERS_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkTYPE_SPECIFIERS_LST_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCLASS_PARAMETER_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkIDENT_DEF_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBOUND_IDENTIFIER_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkCLASS_PARAMETERS_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_PARAMETERS_LST_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCLASS_BOUNDS_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_BOUNDS_LST_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCLASS_ID_DEF_POLY_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkCLASS_ID_DEF_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBUILTIN_OPT_CL_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkBUILTIN_OPT_ID_2 ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBUILTIN_OPT_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBUILTIN_OPT_EMPTY_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_BODY_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkCLASS_HEAD_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkCLASS_ATTRIBUTE_VA_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_ATTRIBUTE_EX_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_ATTRIBUTE_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_ATTRIBUTE_ABVA_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_ATTRIBUTE_AB_2 ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_DECLARATION_2 ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
#define Mk0CLASS_DECLARATIONS_2(_coordref) NULLNODEPTR
extern NODEPTR Mk2CLASS_DECLARATIONS_2 ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkCLASS_DECLARATIONS_2 ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkASSERTION_STATEMENT ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkRAISE_STATEMENT ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkRETURN_STATEMENT ELI_ARG((POSITION *_coordref));
extern NODEPTR MkRESUME_STATEMENT ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBREAK_STATEMENT ELI_ARG((POSITION *_coordref));
extern NODEPTR MkLOOP ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkLOOP_EXP ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkTYPES_LST ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkTYPES_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkWHEN_TYPES_BLOCK ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkWHEN_TYPES_BLOCKS_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkWHEN_TYPES_BLOCKS ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkTYPE_CASE_STATEMENT_ATT ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkTYPE_CASE_STATEMENT ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCASE_LABEL_DES ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkCASE_LABEL_VALUE ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkLABEL_RANGE ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkLABEL_RANGE_SINGLE ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
#define Mk0LABEL_LIST(_coordref) NULLNODEPTR
extern NODEPTR Mk2LABEL_LIST ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkLABEL_LIST ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkWHEN_LABEL_STMT ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkWHEN_LABEL_STMTS_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkWHEN_LABEL_STMTS ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCASE_STATEMENT ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCOND_STATEMENT_ELSE ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkCOND_STATEMENT ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkEXCEPTION_TYPES_LST ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkEXCEPTION_TYPES_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkWHEN_EXCEPTION_STMT ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkWHEN_EXCEPTION_STMTS_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkWHEN_EXCEPTION_STMTS ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkEXCEPTIONS ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkEXCEPTIONS_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBEGIN_BLOCK ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkASSIGNMENT ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_ASSERT ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_RAISE ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_RETURN ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_RESUME ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_EXP ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_BREAK ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_LOOP ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_TYPE_CASE ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_CASE ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_COND ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_BEGIN ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_ASSIGN ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTATEMENTS_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkLOCAL_STREAM_DECL ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkLOCAL_DECLS_STREAM ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkLOCAL_DECLS_ATT ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkLOCAL_DECLS_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBLOCK ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkBUILTIN_INST_CLRTYPE ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkBUILTIN_INST_TYPE ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkBUILTIN_INST_STR ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBUILTIN_INSTS_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBUILTIN_INSTS ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkMETHOD_BODY_STATIC_BUILTIN ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkMETHOD_BODY_BUILTIN ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkLINKER_SYMBOL ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkLINKER_SYMBOL_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkFOREIGN_LANGUAGE ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkMETHOD_BODY_FOREIGN ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkMETHOD_BODY_AB ELI_ARG((POSITION *_coordref));
extern NODEPTR MkMETHOD_BODY ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkPARAMETER_SPEC ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
#define Mk0PARAMETERS(_coordref) NULLNODEPTR
extern NODEPTR Mk2PARAMETERS ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkPARAMETERS ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkMETHOD_IDENT_DEF ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkMETHOD_DECL ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3, NODEPTR _desc4));
extern NODEPTR MkIDENTIFIERS ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkIDENTIFIERS_LST ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_SPEC ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_DECL_CONST_TYPE_CONST ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_DECL_TYPE_CONST ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_DECL_CONST_EXP ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_DECL_EXP ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkATTR_DECL ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkATTR_ACCESS_SH_RO ELI_ARG((POSITION *_coordref));
extern NODEPTR MkATTR_ACCESS_RO ELI_ARG((POSITION *_coordref));
extern NODEPTR MkATTR_ACCESS_SH ELI_ARG((POSITION *_coordref));
extern NODEPTR MkFEATURE_STREAM ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkFEATURE_METH ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkFEATURE_ATT ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkFEATURE_ATT_ACC ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkFEATURE_DECL_PRIV ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkFEATURE_DECL ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
#define Mk0FEATURE_DECLS(_coordref) NULLNODEPTR
extern NODEPTR Mk2FEATURE_DECLS ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkFEATURE_DECLS ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkFEATURE_ID_USE ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkFEATURE_SPEC_STREAM ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkFEATURE_SPEC ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkIDENT_MOD ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkMODIFICATION_NAME ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkMODIFICATION_OUT ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkMODIFICATION_ONLY ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
#define Mk0MODIFICATIONS(_coordref) NULLNODEPTR
extern NODEPTR Mk2MODIFICATIONS ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkMODIFICATIONS ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkINHERITANCE_INC_ONLY ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkINHERITANCE_INCLUDE ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkINHERITANCE_LIKE ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkINHERITANCE_PRIV ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkINHERITANCES_LST ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkINHERITANCES_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkDIRECT_STREAM_CALL ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCOERCION ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTR_CONSTANT ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkSTR_CONSTANTS ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkSTR_CONSTANTS_LST ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkVALUE_VOID ELI_ARG((POSITION *_coordref));
extern NODEPTR MkVALUE_SED ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkVALUE_OCT ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkVALUE_STR ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkVALUE_CHAR ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkVALUE_BOOL ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkVALUE_FLOAT ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkVALUE_INT ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBOUND_METHOD ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkNAMED_EXPRESSION ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
#define Mk0NAMED_EXPRESSIONS(_coordref) NULLNODEPTR
extern NODEPTR Mk2NAMED_EXPRESSIONS ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkNAMED_EXPRESSIONS ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkAGG_ID_DEF ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkAGGREGATE_NAMED ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkAGGREGATE ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_CONSTRUCTOR_SAME_AGG ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_CONSTRUCTOR_SAME ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_CONSTRUCTOR_DES ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkTYPE_CONSTRUCTOR_AGG ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_CONSTRUCTOR_CLASS ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkTYPE_CONSTRUCTOR_CL_AGG ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkQUAL_FEATURE_ID_USE ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkQUALIFICATION_TYPE ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkQUALIFICATION_EXP ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkSTD_METHOD_CALL ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkOBJ_ID_USE ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkNAME_NOT ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_POW ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_MOD ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_DIV ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_QUOTIENT ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_STAR ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkNAME_MINUS ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_PLUS ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_GT_EQ ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_GT ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_LT_EQ ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_LT ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_EQ ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_QUESTION ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_GRAVE ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_TILDE ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_STROKE ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_BACKSLASH ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_STR_IN ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_STR_OUT ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkNAME_OBJ ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkNAME_LEFT_SQ_BRACKET ELI_ARG((POSITION *_coordref));
extern NODEPTR MkEXPRESSION_AND ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkEXPRESSION_OR ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkEXPRESSION_STREAM ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_METH ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_COERCION ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_VALUE ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_BOUND ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_CONS ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkEXPRESSION_STAR ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkDESIGNATOR_QUAL ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkDESIGNATOR_METH ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkDESIGNATOR_EXP ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkDESIGNATOR_NAME ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkARGUMENT_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkARGUMENT_INOUT ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkARGUMENT_OUT ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkARGUMENT_EXP ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkARGUMENTS_LST ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkARGUMENTS_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBOUND_EXP ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
#define Mk0BOUNDS(_coordref) NULLNODEPTR
extern NODEPTR Mk2BOUNDS ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkBOUNDS ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkCLASS_ID_USE ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkPARAMETER_KIND_INOUT ELI_ARG((POSITION *_coordref));
extern NODEPTR MkPARAMETER_KIND_OUT ELI_ARG((POSITION *_coordref));
extern NODEPTR MkPARAMETER_KIND_ONCE ELI_ARG((POSITION *_coordref));
extern NODEPTR MkPARAMETER_KIND_IN ELI_ARG((POSITION *_coordref));
extern NODEPTR MkPARAMETER_TYPE ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
#define Mk0PARAMETER_TYPES(_coordref) NULLNODEPTR
extern NODEPTR Mk2PARAMETER_TYPES ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkPARAMETER_TYPES ELI_ARG((POSITION *_coordref, NODEPTR t));
extern NODEPTR MkMETHOD_SPECIFICATION ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCLASS_ARGUMENT ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkCLASS_ARGUMENTS_LST ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCLASS_ARGUMENTS_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_SPECIFIER ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkTYPE_SPECIFIER_STREAM ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_SPECIFIER_SAME ELI_ARG((POSITION *_coordref));
extern NODEPTR MkTYPE_SPECIFIER_SAME_POLY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkTYPE_SPECIFIER_PROC ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_SPECIFIER_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkTYPE_SPECIFIER_CL ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_SPECIFIER_CL_POLY ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkTYPE_SPECIFIERS_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkTYPE_SPECIFIERS_LST ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCLASS_PARAMETER ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkIDENT_DEF ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBOUND_IDENTIFIER_STAR ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBOUND_IDENTIFIER ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkCLASS_PARAMETERS_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_PARAMETERS_LST ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCLASS_BOUNDS_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_BOUNDS_LST ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2));
extern NODEPTR MkCLASS_ID_DEF ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBUILTIN_OPT_CL ELI_ARG((POSITION *_coordref, NODEPTR _desc1));
extern NODEPTR MkBUILTIN_OPT_ID ELI_ARG((POSITION *_coordref, int _TERM1));
extern NODEPTR MkBUILTIN_OPT ELI_ARG((POSITION *_coordref));
extern NODEPTR MkBUILTIN_OPT_EMPTY ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_BODY ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkCLASS_HEAD ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
extern NODEPTR MkCLASS_ATTRIBUTE_VA ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_ATTRIBUTE_EX ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_ATTRIBUTE ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_ATTRIBUTE_ABVA ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_ATTRIBUTE_AB ELI_ARG((POSITION *_coordref));
extern NODEPTR MkCLASS_DECLARATION ELI_ARG((POSITION *_coordref, NODEPTR _desc1, NODEPTR _desc2, NODEPTR _desc3));
#define Mk0CLASS_DECLARATIONS(_coordref) NULLNODEPTR
extern NODEPTR Mk2CLASS_DECLARATIONS ELI_ARG((POSITION *_coordref, NODEPTR l, NODEPTR r));
extern NODEPTR MkCLASS_DECLARATIONS ELI_ARG((POSITION *_coordref, NODEPTR t));
#define Mkstar(pos,val) (val)
#define Mkinteger_number(pos,val) (val)
#define Mkfloating_number(pos,val) (val)
#define Mkboolean_value(pos,val) (val)
#define Mkcharacterconst(pos,val) (val)
#define Mkoctal_number(pos,val) (val)
#define Mksedecimal_number(pos,val) (val)
#define Mkidentifier(pos,val) (val)
#define Mkstringconst(pos,val) (val)
#endif
